import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Merriweather,
  Inter,
  Poppins,
  Roboto,
  Playfair_Display,
  Roboto_Mono,
} from "next/font/google";
import "./globals.css";
import "./tiptap.css";
import { Footer } from "@/components/layout/footer";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const merriweather = Merriweather({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-merriweather",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair-display",
  weight: ["400", "700"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
  weight: ["400", "500"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${merriweather.variable} ${inter.variable} ${poppins.variable} ${roboto.variable} ${playfairDisplay.variable} ${robotoMono.variable} ${geistMono.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          {/* <Footer /> */}
          <Toaster richColors position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
